### ISSUE TITLE
explosion rollback still rolling back tnt explosions

### ISSUE THREAD

**Issue by teozfrank** [ElgarL/Towny#112]
I have my config setup to just rollback creeper explosions as i just want to allow tnt explosions in the wild to be allowed. Towny keeps rolling back the tnt explosions even though it is removed from the entities list. My config is as follows:

```
wild_revert_on_mob_explosion:
  # Enabling this will slowly regenerate holes created in the
  # wilderness by monsters exploding.
  enabled: 'true'
  entities: Creeper
  delay: 20s
```
