### ISSUE TITLE
Rollback is deleting all blocks on unclaim 0.79.1.3

### ISSUE THREAD

**Issue by SERVERCONSOLE** [ElgarL/Towny#6]
I just did a completely fresh install of Towny 0.79.1.3. When a plot is unclaimed, it starts deleting ALL blocks in the plot. Reclaiming the plot will stop the deletion process. Also even though the rollback time is set for 20M, it deletes blocks at the rate of one per second.

This is the config I am using for the rollback function.
# World management settings to deal with un/claiming plots

  plot_management:

```
block_delete:
  enabled: 'true'
  # These items will be deleted upon a plot being unclaimed
  unclaim_delete: 26,50,55,63,64,68,70,71,72,75,76,93,94

mayor_plotblock_delete:
  enabled: 'true'
  # These items will be deleted upon a mayor using /plot clear
  # To disable deleting replace the current entries with NONE.
  mayor_plot_delete: WALL_SIGN,SIGN_POST

revert_on_unclaim:
  # *** WARNING***
  # If this is enabled any town plots which become unclaimed will
  # slowly be reverted to a snapshot taken before the plot was claimed.
  #
  # Regeneration will only work if the plot was
  # claimed under version 0.76.2, or
  # later with this feature enabled
  #
  # If you allow players to break/build in the wild the snapshot will
  # include any changes made before the plot was claimed.
  enabled: 'true'
  speed: 20m
  # These block types will NOT be regenerated
  block_ignore: 14,21,22,41,42,48,50,52,56,57,63,68,89
```
